//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Project2_4team {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddCourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddCourse() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Education_Project2_4team.AddCourse", typeof(AddCourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Выберете категорию&quot;.
        /// </summary>
        internal static string AddCourse_CategoryRequired {
            get {
                return ResourceManager.GetString("AddCourse_CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &quot;Курс не найден.&quot;.
        /// </summary>
        internal static string AddCourse_CourseNotFound {
            get {
                return ResourceManager.GetString("AddCourse_CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &quot;Введите описание курса&quot;.
        /// </summary>
        internal static string AddCourse_DescriptionRequired {
            get {
                return ResourceManager.GetString("AddCourse_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Выберете продолжительность курса&quot;.
        /// </summary>
        internal static string AddCourse_DurationRequired {
            get {
                return ResourceManager.GetString("AddCourse_DurationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Выберете форму обучения&quot;.
        /// </summary>
        internal static string AddCourse_EduFormRequired {
            get {
                return ResourceManager.GetString("AddCourse_EduFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Выберете уровень подготовки&quot;.
        /// </summary>
        internal static string AddCourse_LevelRequired {
            get {
                return ResourceManager.GetString("AddCourse_LevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Ошибка при сохранении курса: {0}&quot;.
        /// </summary>
        internal static string AddCourse_SaveError {
            get {
                return ResourceManager.GetString("AddCourse_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &quot;Курс успешно добавлен!&quot;.
        /// </summary>
        internal static string AddCourse_SaveSuccess_Add {
            get {
                return ResourceManager.GetString("AddCourse_SaveSuccess_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Курс успешно обновлён!&quot;.
        /// </summary>
        internal static string AddCourse_SaveSuccess_Update {
            get {
                return ResourceManager.GetString("AddCourse_SaveSuccess_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Введите название курса&quot;.
        /// </summary>
        internal static string AddCourse_TitleRequired {
            get {
                return ResourceManager.GetString("AddCourse_TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string ButtonSaveText {
            get {
                return ResourceManager.GetString("ButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технические науки;Гуманитарные науки;Естественные науки;Творчество.
        /// </summary>
        internal static string ComboBoxCategoryItems {
            get {
                return ResourceManager.GetString("ComboBoxCategoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        internal static string ComboBoxCategoryPrompt {
            get {
                return ResourceManager.GetString("ComboBoxCategoryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 месяц;3 месяца;6 месяцев;1 год.
        /// </summary>
        internal static string ComboBoxDurationItems {
            get {
                return ResourceManager.GetString("ComboBoxDurationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжительность курса.
        /// </summary>
        internal static string ComboBoxDurationPrompt {
            get {
                return ResourceManager.GetString("ComboBoxDurationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очная;Онлайн;Смешанная.
        /// </summary>
        internal static string ComboBoxFormItems {
            get {
                return ResourceManager.GetString("ComboBoxFormItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма обучения.
        /// </summary>
        internal static string ComboBoxFormPrompt {
            get {
                return ResourceManager.GetString("ComboBoxFormPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальный;Средний;Продвинутый.
        /// </summary>
        internal static string ComboBoxLevelItems {
            get {
                return ResourceManager.GetString("ComboBoxLevelItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень подготовки.
        /// </summary>
        internal static string ComboBoxLevelPrompt {
            get {
                return ResourceManager.GetString("ComboBoxLevelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Добавить курс.
        /// </summary>
        internal static string FormTitleAddCourse {
            get {
                return ResourceManager.GetString("FormTitleAddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание:.
        /// </summary>
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о курсе.
        /// </summary>
        internal static string LabelMainHeader {
            get {
                return ResourceManager.GetString("LabelMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название:.
        /// </summary>
        internal static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
    }
}
