//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Project2_4team {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class CoursesForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoursesForm() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Education_Project2_4team.CoursesForm", typeof(CoursesForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить курс.
        /// </summary>
        internal static string ButtonAddCourseText {
            get {
                return ResourceManager.GetString("ButtonAddCourseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить в избранное.
        /// </summary>
        internal static string ButtonAddToFavouritesText {
            get {
                return ResourceManager.GetString("ButtonAddToFavouritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить курс.
        /// </summary>
        internal static string ButtonDeleteCourseText {
            get {
                return ResourceManager.GetString("ButtonDeleteCourseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        internal static string ButtonFilterText {
            get {
                return ResourceManager.GetString("ButtonFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти в избранное.
        /// </summary>
        internal static string ButtonOpenFavouritesText {
            get {
                return ResourceManager.GetString("ButtonOpenFavouritesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        internal static string ButtonRedactText {
            get {
                return ResourceManager.GetString("ButtonRedactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все категории;Технические науки;Гуманитарные науки;Естественные науки;Творчество.
        /// </summary>
        internal static string ComboBoxFilterItems {
            get {
                return ResourceManager.GetString("ComboBoxFilterItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        internal static string ComboBoxFilterPrompt {
            get {
                return ResourceManager.GetString("ComboBoxFilterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только авторизованные пользователи.
        /// </summary>
        internal static string Error_OnlyForAuthorized_AddToFavourites {
            get {
                return ResourceManager.GetString("Error_OnlyForAuthorized_AddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курсы.
        /// </summary>
        internal static string Form_Title {
            get {
                return ResourceManager.GetString("Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курсы с выбранной категорией не найдены.
        /// </summary>
        internal static string Info_NoCoursesWithCategory {
            get {
                return ResourceManager.GetString("Info_NoCoursesWithCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс уже в избранном.
        /// </summary>
        internal static string Message_AlreadyInFavourites {
            get {
                return ResourceManager.GetString("Message_AlreadyInFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить курс {0}?.
        /// </summary>
        internal static string Message_ConfirmDeletion {
            get {
                return ResourceManager.GetString("Message_ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Курс добавлен в избранное.
        /// </summary>
        internal static string Message_CourseAddedToFavourites {
            get {
                return ResourceManager.GetString("Message_CourseAddedToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс успешно удалён.
        /// </summary>
        internal static string Message_CourseDeleted {
            get {
                return ResourceManager.GetString("Message_CourseDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс не найден.
        /// </summary>
        internal static string Message_CourseNotFound {
            get {
                return ResourceManager.GetString("Message_CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список курсов.
        /// </summary>
        internal static string TextBoxTitleText {
            get {
                return ResourceManager.GetString("TextBoxTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите удаление.
        /// </summary>
        internal static string Title_ConfirmationDeletion {
            get {
                return ResourceManager.GetString("Title_ConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        internal static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        internal static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только для пользователей.
        /// </summary>
        internal static string Warning_OnlyForUsers_ViewFavourites {
            get {
                return ResourceManager.GetString("Warning_OnlyForUsers_ViewFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите курс для удаление.
        /// </summary>
        internal static string Warning_SelectCourseForDeletion {
            get {
                return ResourceManager.GetString("Warning_SelectCourseForDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите курс для редактирования.
        /// </summary>
        internal static string Warning_SelectCourseForEditing {
            get {
                return ResourceManager.GetString("Warning_SelectCourseForEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите курс для добавления в избранное.
        /// </summary>
        internal static string Warning_SelectCourseForFavourites {
            get {
                return ResourceManager.GetString("Warning_SelectCourseForFavourites", resourceCulture);
            }
        }
    }
}
