//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Project2_4team {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class questionnare {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal questionnare() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Education_Project2_4team.questionnare", typeof(questionnare).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Технические науки; Гуманитарные науки; Естественные науки; Творчество.
        /// </summary>
        internal static string CategoryOptions {
            get {
                return ResourceManager.GetString("CategoryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        internal static string ComboBoxCategoryDefault {
            get {
                return ResourceManager.GetString("ComboBoxCategoryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжительность курса.
        /// </summary>
        internal static string ComboBoxDurationDefault {
            get {
                return ResourceManager.GetString("ComboBoxDurationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Форма обучения.
        /// </summary>
        internal static string ComboBoxFormDefault {
            get {
                return ResourceManager.GetString("ComboBoxFormDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень подготовки.
        /// </summary>
        internal static string ComboBoxLevelDefault {
            get {
                return ResourceManager.GetString("ComboBoxLevelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 месяц; 3 месяца; 6 месяцев; 1 год.
        /// </summary>
        internal static string DurationOptions {
            get {
                return ResourceManager.GetString("DurationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Очная; Онлайн; Смешанная.
        /// </summary>
        internal static string FormOptions {
            get {
                return ResourceManager.GetString("FormOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &quot;Нет подходящих курсов по заданным параметрам.&quot;.
        /// </summary>
        internal static string Info_NoMatchingCourses {
            get {
                return ResourceManager.GetString("Info_NoMatchingCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анкетирование.
        /// </summary>
        internal static string LabelQuestionnaire {
            get {
                return ResourceManager.GetString("LabelQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальный; Средний; Продвинутый.
        /// </summary>
        internal static string LevelOptions {
            get {
                return ResourceManager.GetString("LevelOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Ошибка&quot;.
        /// </summary>
        internal static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Результат&quot;.
        /// </summary>
        internal static string Title_Result {
            get {
                return ResourceManager.GetString("Title_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;При отсутствии избранных курсов необходимо заполнить все поля анкеты&quot;.
        /// </summary>
        internal static string Warning_EmptyQuestionnaireWithoutFavs {
            get {
                return ResourceManager.GetString("Warning_EmptyQuestionnaireWithoutFavs", resourceCulture);
            }
        }
    }
}
