//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education_Project2_4team {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Education_Project2_4team.Registration", typeof(Registration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        internal static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать пароль.
        /// </summary>
        internal static string CheckBoxShowPassword {
            get {
                return ResourceManager.GetString("CheckBoxShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CheckBoxShowRepeatPassword.
        /// </summary>
        internal static string CheckBoxShowRepeatPassword {
            get {
                return ResourceManager.GetString("CheckBoxShowRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Поле &apos;Имя&apos; не должно быть пустым&quot;.
        /// </summary>
        internal static string Error_EmptyName {
            get {
                return ResourceManager.GetString("Error_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &quot;Поле &apos;Фамилия&apos; не должно быть пустым&quot;.
        /// </summary>
        internal static string Error_EmptySurname {
            get {
                return ResourceManager.GetString("Error_EmptySurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Ошибка: {0}&quot;.
        /// </summary>
        internal static string Error_Generic {
            get {
                return ResourceManager.GetString("Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Логин должен содержать только английские буквы&quot;.
        /// </summary>
        internal static string Error_InvalidLogin {
            get {
                return ResourceManager.GetString("Error_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Пароли не совпадают&quot;.
        /// </summary>
        internal static string Error_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Error_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &quot;Логин должен содержать не менее 4 символов&quot;.
        /// </summary>
        internal static string Error_ShortLogin {
            get {
                return ResourceManager.GetString("Error_ShortLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Пароль должен содержать не менее 8 символов&quot;.
        /// </summary>
        internal static string Error_ShortPassword {
            get {
                return ResourceManager.GetString("Error_ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин:.
        /// </summary>
        internal static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль:.
        /// </summary>
        internal static string LabelRepeatPassword {
            get {
                return ResourceManager.GetString("LabelRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        internal static string LabelSurname {
            get {
                return ResourceManager.GetString("LabelSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Регистрация успешна!&quot;.
        /// </summary>
        internal static string Success_Registration {
            get {
                return ResourceManager.GetString("Success_Registration", resourceCulture);
            }
        }
    }
}
